### ISSUE TITLE
Might do better to contribute to pyupgrade?

### ISSUE THREAD

**Issue by asottile** [ikamensh/flynt#10]
Or at the very least steal the testsuite there since I've done extensive research in this department :)

- [percent format testsuite](https://github.com/asottile/pyupgrade/blob/78b03f2e1682e08214d1f1f19aa8d07115121f12/tests/percent_format_test.py)
- [format testsuite](https://github.com/asottile/pyupgrade/blob/78b03f2e1682e08214d1f1f19aa8d07115121f12/tests/format_literals_test.py)
- [fstrings testsuite](https://github.com/asottile/pyupgrade/blob/78b03f2e1682e08214d1f1f19aa8d07115121f12/tests/fstrings_test.py)

**Comment by ikamensh** [comment]
Hey! Thanks for visiting :)
I think you are generally right, since it makes sense to bring other advantages together with f-strings. 

I am surprised that I found pyupgrade only after writing this myself, and I did search. 
My key use case is one-time upgrade of a legacy project once it drops support for python <3.6. Assuming we work on ./flask:
I currently was able to do basically the same thing that flynt does using 'find flask -name '*.py' -exec pyupgrade {} --py36-plus \;'.

It would probably be more convenient and faster to be able to use following:

```
pyupgrade --py36-plus flask
Traceback (most recent call last):
  File "/Users/ikkamens/.pyenv/versions/3.7.3/bin/pyupgrade", line 10, in <module>
    sys.exit(main())
  File "/Users/ikkamens/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pyupgrade.py", line 1992, in main
    ret |= fix_file(filename, args)
  File "/Users/ikkamens/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pyupgrade.py", line 1947, in fix_file
    with open(filename, 'rb') as fb:
IsADirectoryError: [Errno 21] Is a directory: 'flask'
```

Is there a simple way for people to use pyupgrade without the pre-commit?

**Comment by asottile** [comment]
if it's just one time `pre-commit try-repo https://github.com/asottile/pyupgrade --all-files`

pre-commit is better thought of as a lint runner that happens to know things about git hooks, though it didn't start that way

otherwise no, just use `xargs` / `find` -- no reason to reimplement ala unix philosophy

**Comment by ikamensh** [comment]
Well, there are windows users who don't have a nice CLI :) furthermore many people come to python from data science and similar, and might not be skilled with xargs / find.

I will do the following:
* copy your tests and make sure they work
* potentially simplify my implementation by looking at how you did it / or make pyupgrade a dependency and delegate to it
* print a message at the end of the run with instructions on how to run pyupgrade to get all the benefits of py36+.

**Comment by ikamensh** [comment]
Also using xargs / find means you will edit things in `blacklist = {'.tox', 'venv', 'site-packages', '.eggs'}` directories.

**Comment by asottile** [comment]
pretty much all windows users will have `find` / `xargs` due to installing `git bash`

and yes it will do things on those directories if you're bad at xargs, but `git ls-files -- '*.py' | xargs ...` won't
