### ISSUE TITLE
Support log.<level> statements with sprintf style formatting.

### ISSUE THREAD

**Issue by dsully** [ikamensh/flynt#33]
As the subject line says.

**Comment by ikamensh** [comment]
Hey, can you please elaborate on why it's useful?

**Comment by asottile** [comment]
For instance:

```diff
-logger.warning('event %s at time %d', event_name, time.time())
+logger.warning(f'event {event_name} at time {time.time()}')
```

though ~sometimes you want to defer formatting in log lines (and depending on the situation the eager formatting can affect performance / correctness so this can have some risks associated with it)

**Comment by ikamensh** [comment]
I understand this feature request now. Honestly I find this api of logging really strange - why would you not just use percent yourself, instead of delegating to logging? I am not inclined to spend the effort to include this (and it's a significant effort because I use AST module, to which a function call is another beast entirely from the % BinOp ). Might reconsider if this gets enough +1s, but closed for now.

**Comment by catlee** [comment]
FWIW, doing the string interpolation early can have performance impacts. e.g. logger.debug calls with large objects. Doing `logger.debug("The thing: %s" % big_thing)` will always call `str(big_thing)`. If our log level isn't debug, then this is just a waste of time.

This can result in issues like https://github.com/mozilla-releng/redo/pull/51. IMO best practise is to use `logger.X(message, val1, val2, val3, ...)` so that interpolation can happen lazily.
