### ISSUE TITLE
Some failure examples

### ISSUE THREAD

**Issue by jond01** [ikamensh/flynt#67]
Hi, your tool is very helpful - saves loads of time.

If it will succeed also in these minimal examples, it will be even better:

1.
```python
import numpy as np


normal_fname = 'f'

print("RMS of standard image {:<44}: {}".format(
    normal_fname,
    np.sqrt(np.sum(np.array([1, 2]) ** 2))))

```

2.
```python
PYTHON = 'python.exe'

cmd = '{0} -c "print(\'Hello\')"'.format(PYTHON)
print(cmd)

```

3.
```python
import os


ds_relative = '.'
root_dirs = ['p1', 'p2']

raise ValueError('Could not find datasource "%s" in data path "%s"' %
                 (ds_relative,
                  os.path.pathsep.join(root_dirs)))

```
Thanks

**Comment by ikamensh** [comment]
Regarding your examples:
1), 3) are converted if it fits the line length limit (try adding flag `-ll 999`). Note that it was enabled in one of the latest versions, so you might need to update flynt via pip (`pip install --upgrade flynt` )

2) breaks down because I am using python built-in `tokenizer` module , which behaves surprisingly: `'{0} -c "print(\'Hello\')"'` is parsed as 3 tokens "STRING, NAME, STRING". I expect any format call to be specifically STRING, '.', STRING==format, '(', * ,')'. This apparently has to do with multiple quotes levels. Too complicated to work around this, perhaps this is a minor bug in built-in `tokenize` module.

Too difficult and rare to work around this.
